<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Personne_FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Personne_FormationRepository extends EntityRepository
{
}
